services:
  nginx:
    build: .
    ports:
      # Map container port 80 to the HTTP port defined in .env
      - "${HOST_HTTP_PORT}:80"
      # Map container port 443 to the HTTPS port defined in .env
      - "${HOST_HTTPS_PORT}:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro    # mount your local conf as nginx config inside container (read-only).
      - ./myapp:/usr/share/nginx/html:ro     # mount static files to container webroot.
      - ./ssl:/etc/nginx/ssl:ro             # mount ssl certs to container (read-only).
    restart: unless-stopped


# Why mount instead of COPY?
# Mounting (bind mount) lets you edit files locally and restart the container without rebuilding the image. For development/demo this is handy.